//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCodtela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCodtela()
        {
            this.tbtelaprocol = new HashSet<tbtelaprocol>();
        }
    
        public int idCodTela { get; set; }
        public string CodTela { get; set; }
        public Nullable<int> idcolor { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idcliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbtelaprocol> tbtelaprocol { get; set; }
    }
}
