//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcontenedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcontenedor()
        {
            this.tbPoCont = new HashSet<tbPoCont>();
        }
    
        public int idcontenedor { get; set; }
        public string contenedor { get; set; }
        public Nullable<int> totalRollos { get; set; }
        public Nullable<double> totalYardas { get; set; }
        public string fechaRecibido { get; set; }
        public string fechaDescargado { get; set; }
        public string fechaEnvio { get; set; }
        public string estado { get; set; }
        public string userName { get; set; }
        public Nullable<int> idcliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPoCont> tbPoCont { get; set; }
    }
}
