//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPoCont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPoCont()
        {
            this.tbrollos = new HashSet<tbrollos>();
        }
    
        public int idPoCont { get; set; }
        public Nullable<System.DateTime> daterecuv { get; set; }
        public string invoicePO { get; set; }
        public Nullable<int> idcontenedor { get; set; }
        public string estado { get; set; }
    
        public virtual tbcontenedor tbcontenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbrollos> tbrollos { get; set; }
    }
}
