//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbswatch
    {
        public int idswatches { get; set; }
        public int idrollo { get; set; }
        public Nullable<double> x1 { get; set; }
        public Nullable<double> x2 { get; set; }
        public Nullable<double> x3 { get; set; }
        public Nullable<double> y1 { get; set; }
        public Nullable<double> y2 { get; set; }
        public Nullable<double> y3 { get; set; }
        public Nullable<double> p1 { get; set; }
        public Nullable<double> p2 { get; set; }
        public Nullable<double> p3 { get; set; }
        public Nullable<double> p4 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public Nullable<double> a1 { get; set; }
        public Nullable<double> a2 { get; set; }
        public Nullable<double> a3 { get; set; }
        public Nullable<double> b1 { get; set; }
        public Nullable<double> b2 { get; set; }
        public Nullable<double> b3 { get; set; }
        public Nullable<System.DateTime> fechaP2 { get; set; }
        public string usuarioP2 { get; set; }
        public Nullable<double> c1 { get; set; }
        public Nullable<double> c2 { get; set; }
        public Nullable<double> c3 { get; set; }
        public Nullable<double> z1 { get; set; }
        public Nullable<double> z2 { get; set; }
        public Nullable<double> z3 { get; set; }
        public Nullable<System.DateTime> fechaP3 { get; set; }
        public string usuarioP3 { get; set; }
    
        public virtual tbrollos tbrollos { get; set; }
    }
}
