//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbtelaprocol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbtelaprocol()
        {
            this.tbrollos = new HashSet<tbrollos>();
        }
    
        public int idtpc { get; set; }
        public Nullable<int> idtela { get; set; }
        public Nullable<int> idproveedor { get; set; }
        public string descripcion { get; set; }
        public string procod { get; set; }
        public Nullable<double> MarkerWidth { get; set; }
    
        public virtual tbCodtela tbCodtela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbrollos> tbrollos { get; set; }
    }
}
